// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func GetTrip() *Trip {
	airplane := NewAirplane()
	dunHuang := NewDunHuang()
	trip := NewTrip(airplane, dunHuang)
	return trip
}
