// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: wellk.proto

package main

import (
	fmt "fmt"
	gogoproto "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
//const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Timestamp from public import google/protobuf/timestamp.proto
type Timestamp = timestamppb.Timestamp

// Duration from public import google/protobuf/duration.proto
type Duration = durationpb.Duration

var E_GoprotoEnumPrefix = gogoproto.E_GoprotoEnumPrefix

var E_GoprotoEnumStringer = gogoproto.E_GoprotoEnumStringer

var E_EnumStringer = gogoproto.E_EnumStringer

var E_EnumCustomname = gogoproto.E_EnumCustomname

var E_Enumdecl = gogoproto.E_Enumdecl

var E_EnumvalueCustomname = gogoproto.E_EnumvalueCustomname

var E_GoprotoGettersAll = gogoproto.E_GoprotoGettersAll

var E_GoprotoEnumPrefixAll = gogoproto.E_GoprotoEnumPrefixAll

var E_GoprotoStringerAll = gogoproto.E_GoprotoStringerAll

var E_VerboseEqualAll = gogoproto.E_VerboseEqualAll

var E_FaceAll = gogoproto.E_FaceAll

var E_GostringAll = gogoproto.E_GostringAll

var E_PopulateAll = gogoproto.E_PopulateAll

var E_StringerAll = gogoproto.E_StringerAll

var E_OnlyoneAll = gogoproto.E_OnlyoneAll

var E_EqualAll = gogoproto.E_EqualAll

var E_DescriptionAll = gogoproto.E_DescriptionAll

var E_TestgenAll = gogoproto.E_TestgenAll

var E_BenchgenAll = gogoproto.E_BenchgenAll

var E_MarshalerAll = gogoproto.E_MarshalerAll

var E_UnmarshalerAll = gogoproto.E_UnmarshalerAll

var E_StableMarshalerAll = gogoproto.E_StableMarshalerAll

var E_SizerAll = gogoproto.E_SizerAll

var E_GoprotoEnumStringerAll = gogoproto.E_GoprotoEnumStringerAll

var E_EnumStringerAll = gogoproto.E_EnumStringerAll

var E_UnsafeMarshalerAll = gogoproto.E_UnsafeMarshalerAll

var E_UnsafeUnmarshalerAll = gogoproto.E_UnsafeUnmarshalerAll

var E_GoprotoExtensionsMapAll = gogoproto.E_GoprotoExtensionsMapAll

var E_GoprotoUnrecognizedAll = gogoproto.E_GoprotoUnrecognizedAll

var E_GogoprotoImport = gogoproto.E_GogoprotoImport

var E_ProtosizerAll = gogoproto.E_ProtosizerAll

var E_CompareAll = gogoproto.E_CompareAll

var E_TypedeclAll = gogoproto.E_TypedeclAll

var E_EnumdeclAll = gogoproto.E_EnumdeclAll

var E_GoprotoRegistration = gogoproto.E_GoprotoRegistration

var E_MessagenameAll = gogoproto.E_MessagenameAll

var E_GoprotoSizecacheAll = gogoproto.E_GoprotoSizecacheAll

var E_GoprotoUnkeyedAll = gogoproto.E_GoprotoUnkeyedAll

var E_GoprotoGetters = gogoproto.E_GoprotoGetters

var E_GoprotoStringer = gogoproto.E_GoprotoStringer

var E_VerboseEqual = gogoproto.E_VerboseEqual

var E_Face = gogoproto.E_Face

var E_Gostring = gogoproto.E_Gostring

var E_Populate = gogoproto.E_Populate

var E_Stringer = gogoproto.E_Stringer

var E_Onlyone = gogoproto.E_Onlyone

var E_Equal = gogoproto.E_Equal

var E_Description = gogoproto.E_Description

var E_Testgen = gogoproto.E_Testgen

var E_Benchgen = gogoproto.E_Benchgen

var E_Marshaler = gogoproto.E_Marshaler

var E_Unmarshaler = gogoproto.E_Unmarshaler

var E_StableMarshaler = gogoproto.E_StableMarshaler

var E_Sizer = gogoproto.E_Sizer

var E_UnsafeMarshaler = gogoproto.E_UnsafeMarshaler

var E_UnsafeUnmarshaler = gogoproto.E_UnsafeUnmarshaler

var E_GoprotoExtensionsMap = gogoproto.E_GoprotoExtensionsMap

var E_GoprotoUnrecognized = gogoproto.E_GoprotoUnrecognized

var E_Protosizer = gogoproto.E_Protosizer

var E_Compare = gogoproto.E_Compare

var E_Typedecl = gogoproto.E_Typedecl

var E_Messagename = gogoproto.E_Messagename

var E_GoprotoSizecache = gogoproto.E_GoprotoSizecache

var E_GoprotoUnkeyed = gogoproto.E_GoprotoUnkeyed

var E_Nullable = gogoproto.E_Nullable

var E_Embed = gogoproto.E_Embed

var E_Customtype = gogoproto.E_Customtype

var E_Customname = gogoproto.E_Customname

var E_Jsontag = gogoproto.E_Jsontag

var E_Moretags = gogoproto.E_Moretags

var E_Casttype = gogoproto.E_Casttype

var E_Castkey = gogoproto.E_Castkey

var E_Castvalue = gogoproto.E_Castvalue

var E_Stdtime = gogoproto.E_Stdtime

var E_Stdduration = gogoproto.E_Stdduration

var E_Wktpointer = gogoproto.E_Wktpointer

type WellKnownTypes struct {
	Now                  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Now,proto3" json:"now"`
	Took                 *durationpb.Duration   `protobuf:"bytes,2,opt,name=Took,proto3" json:"took"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *WellKnownTypes) Reset()         { *m = WellKnownTypes{} }
func (m *WellKnownTypes) String() string { return proto.CompactTextString(m) }
func (*WellKnownTypes) ProtoMessage()    {}
func (*WellKnownTypes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e450a4f639222ea3, []int{0}
}
func (m *WellKnownTypes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WellKnownTypes.Unmarshal(m, b)
}
func (m *WellKnownTypes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WellKnownTypes.Marshal(b, m, deterministic)
}
func (m *WellKnownTypes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WellKnownTypes.Merge(m, src)
}
func (m *WellKnownTypes) XXX_Size() int {
	return xxx_messageInfo_WellKnownTypes.Size(m)
}
func (m *WellKnownTypes) XXX_DiscardUnknown() {
	xxx_messageInfo_WellKnownTypes.DiscardUnknown(m)
}

var xxx_messageInfo_WellKnownTypes proto.InternalMessageInfo

func (m *WellKnownTypes) GetNow() *timestamppb.Timestamp {
	if m != nil {
		return m.Now
	}
	return nil
}

func (m *WellKnownTypes) GetTook() *durationpb.Duration {
	if m != nil {
		return m.Took
	}
	return nil
}

func init() {
	proto.RegisterType((*WellKnownTypes)(nil), "main.WellKnownTypes")
}

func init() { proto.RegisterFile("wellk.proto", fileDescriptor_e450a4f639222ea3) }

var fileDescriptor_e450a4f639222ea3 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4f, 0xcd, 0xc9,
	0xc9, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x93, 0x92, 0x4f,
	0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x25, 0x95, 0xa6, 0xe9, 0x97, 0x64, 0xe6, 0xa6,
	0x16, 0x97, 0x24, 0xe6, 0x16, 0x40, 0x94, 0x49, 0xc9, 0xa1, 0x2b, 0x48, 0x29, 0x2d, 0x4a, 0x2c,
	0xc9, 0xcc, 0xcf, 0x83, 0xca, 0xeb, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0xa7, 0xe7, 0xa7, 0xe7, 0x23, 0x14, 0x82, 0x78, 0x60, 0x0e, 0x98, 0x05, 0x51, 0xae, 0xd4,
	0xc0, 0xc8, 0xc5, 0x17, 0x9e, 0x9a, 0x93, 0xe3, 0x9d, 0x97, 0x5f, 0x9e, 0x17, 0x52, 0x59, 0x90,
	0x5a, 0x2c, 0x64, 0xca, 0xc5, 0xec, 0x97, 0x5f, 0x2e, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0x24,
	0xa5, 0x07, 0xb1, 0x4f, 0x0f, 0x66, 0x8c, 0x5e, 0x08, 0xcc, 0x41, 0x4e, 0xec, 0xaf, 0xee, 0xc9,
	0x33, 0xe7, 0xe5, 0x97, 0x07, 0x81, 0xd4, 0x0b, 0x99, 0x73, 0xb1, 0x84, 0xe4, 0xe7, 0x67, 0x4b,
	0x30, 0x81, 0xf5, 0x49, 0x62, 0xe8, 0x73, 0x81, 0xba, 0xd3, 0x89, 0xe3, 0xd5, 0x3d, 0x79, 0x96,
	0x92, 0xfc, 0xfc, 0xec, 0x20, 0xb0, 0x06, 0x27, 0xce, 0x28, 0x76, 0x3d, 0x7d, 0x6b, 0x90, 0xef,
	0x03, 0x18, 0x02, 0x18, 0x03, 0x98, 0x92, 0xd8, 0xc0, 0x7a, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xe0, 0xaa, 0xba, 0x4e, 0x1f, 0x01, 0x00, 0x00,
}
